{% set name = "xicam.plugins" %}
{% set version = "2.2.5" %}
{% set sha256 = "d029bc2d0ecb1af7c0bee8e37e0ab7e337841889b76a61393d9ef4791cbab543" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/synchrotrons/Xi-cam.plugins/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - appdirs
    - astropy
    - entrypoints
    - pyqt >=5
    - pyqtgraph
    - requests
    - signalslot
    - virtualenv
    - xicam.core
    - yapsy

test:
  imports:
    - xicam.plugins

about:
  home: https://github.com/synchrotrons/Xi-cam.plugins
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The CAMERA platform for synchrotron data management, visualization, and reduction.
  description: |
    The xicam.gui package contains all gui code of the Xi-cam platform, as part
    of the xicam namespace package. For the backend components, see
    "xicam.core".
